# Generated by Django 4.2.7 on 2023-11-20 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YugiohCardsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeusCads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=100)),
                ('usuario_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YugiohCardsApp.usuario')),
            ],
        ),
    ]
