# Generated by Django 4.2.7 on 2023-11-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YugiohCardsApp', '0002_seuscads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seuscads',
            name='usuario_cad',
        ),
    ]
